version: '3'
services:
  db:
    image: postgres:13
    tty: true
    stdin_open: true
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 8080
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: .
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes:
      - ./:/app:cached
    working_dir: /app
volumes:
  db-data:
